export interface PlaceCoordinates {
  lat: number;
  lng: number;
  city: string;
  district: string;
  highway: string;
  address: string;
  state?: string;
}

export const INDIA_PLACES_REGISTRY: Record<string, PlaceCoordinates> = {
  visakhapatnam: {
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    city: "Visakhapatnam",
    lat: 17.6868,
    lng: 83.2185,
    highway: "State Highway",
    address: "Central area, Visakhapatnam, Andhra Pradesh",
  },
  vijayawada: {
    state: "Andhra Pradesh",
    district: "Vijayawada",
    city: "Vijayawada",
    lat: 16.5062,
    lng: 80.648,
    highway: "State Highway",
    address: "Central area, Vijayawada, Andhra Pradesh",
  },
  itanagar: {
    state: "Arunachal Pradesh",
    district: "Papum Pare",
    city: "Itanagar",
    lat: 27.0844,
    lng: 93.6053,
    highway: "State Highway",
    address: "Central area, Itanagar, Arunachal Pradesh",
  },
  guwahati: {
    state: "Assam",
    district: "Kamrup Metropolitan",
    city: "Guwahati",
    lat: 26.1445,
    lng: 91.7362,
    highway: "State Highway",
    address: "Central area, Guwahati, Assam",
  },
  patna: {
    state: "Bihar",
    district: "Patna",
    city: "Patna",
    lat: 25.5941,
    lng: 85.1376,
    highway: "State Highway",
    address: "Central area, Patna, Bihar",
  },
  raipur: {
    state: "Chhattisgarh",
    district: "Raipur",
    city: "Raipur",
    lat: 21.2514,
    lng: 81.6296,
    highway: "State Highway",
    address: "Central area, Raipur, Chhattisgarh",
  },
  panaji: {
    state: "Goa",
    district: "North Goa",
    city: "Panaji",
    lat: 15.4909,
    lng: 73.8278,
    highway: "State Highway",
    address: "Central area, Panaji, Goa",
  },
  ahmedabad: {
    state: "Gujarat",
    district: "Ahmedabad",
    city: "Ahmedabad",
    lat: 23.0225,
    lng: 72.5714,
    highway: "State Highway",
    address: "Central area, Ahmedabad, Gujarat",
  },
  surat: {
    state: "Gujarat",
    district: "Surat",
    city: "Surat",
    lat: 21.1702,
    lng: 72.8311,
    highway: "State Highway",
    address: "Central area, Surat, Gujarat",
  },
  gurugram: {
    state: "Haryana",
    district: "Gurugram",
    city: "Gurugram",
    lat: 28.4595,
    lng: 77.0266,
    highway: "State Highway",
    address: "Central area, Gurugram, Haryana",
  },
  shimla: {
    state: "Himachal Pradesh",
    district: "Shimla",
    city: "Shimla",
    lat: 31.1048,
    lng: 77.1734,
    highway: "State Highway",
    address: "Central area, Shimla, Himachal Pradesh",
  },
  ranchi: {
    state: "Jharkhand",
    district: "Ranchi",
    city: "Ranchi",
    lat: 23.3441,
    lng: 85.3096,
    highway: "State Highway",
    address: "Central area, Ranchi, Jharkhand",
  },
  bengaluru: {
    state: "Karnataka",
    district: "Bengaluru Urban",
    city: "Bengaluru",
    lat: 12.9716,
    lng: 77.5946,
    highway: "State Highway",
    address: "Central area, Bengaluru, Karnataka",
  },
  mysuru: {
    state: "Karnataka",
    district: "Mysuru",
    city: "Mysuru",
    lat: 12.2958,
    lng: 76.6394,
    highway: "State Highway",
    address: "Central area, Mysuru, Karnataka",
  },
  thiruvananthapuram: {
    state: "Kerala",
    district: "Thiruvananthapuram",
    city: "Thiruvananthapuram",
    lat: 8.5241,
    lng: 76.9366,
    highway: "State Highway",
    address: "Central area, Thiruvananthapuram, Kerala",
  },
  kochi: {
    state: "Kerala",
    district: "Ernakulam",
    city: "Kochi",
    lat: 9.9312,
    lng: 76.2673,
    highway: "State Highway",
    address: "Central area, Kochi, Kerala",
  },
  bhopal: {
    state: "Madhya Pradesh",
    district: "Bhopal",
    city: "Bhopal",
    lat: 23.2599,
    lng: 77.4126,
    highway: "State Highway",
    address: "Central area, Bhopal, Madhya Pradesh",
  },
  indore: {
    state: "Madhya Pradesh",
    district: "Indore",
    city: "Indore",
    lat: 22.7196,
    lng: 75.8577,
    highway: "State Highway",
    address: "Central area, Indore, Madhya Pradesh",
  },
  mumbai: {
    state: "Maharashtra",
    district: "Mumbai District",
    city: "Mumbai",
    lat: 19.076,
    lng: 72.8777,
    highway: "State Highway",
    address: "Central area, Mumbai, Maharashtra",
  },
  pune: {
    state: "Maharashtra",
    district: "Pune",
    city: "Pune",
    lat: 18.5204,
    lng: 73.8567,
    highway: "State Highway",
    address: "Central area, Pune, Maharashtra",
  },
  imphal: {
    state: "Manipur",
    district: "Imphal West",
    city: "Imphal",
    lat: 24.817,
    lng: 93.9368,
    highway: "State Highway",
    address: "Central area, Imphal, Manipur",
  },
  shillong: {
    state: "Meghalaya",
    district: "East Khasi Hills",
    city: "Shillong",
    lat: 25.5788,
    lng: 91.8933,
    highway: "State Highway",
    address: "Central area, Shillong, Meghalaya",
  },
  aizawl: {
    state: "Mizoram",
    district: "Aizawl",
    city: "Aizawl",
    lat: 23.7271,
    lng: 92.7176,
    highway: "State Highway",
    address: "Central area, Aizawl, Mizoram",
  },
  kohima: {
    state: "Nagaland",
    district: "Kohima",
    city: "Kohima",
    lat: 25.6751,
    lng: 94.1086,
    highway: "State Highway",
    address: "Central area, Kohima, Nagaland",
  },
  bhubaneswar: {
    state: "Odisha",
    district: "Khordha",
    city: "Bhubaneswar",
    lat: 20.2961,
    lng: 85.8245,
    highway: "State Highway",
    address: "Central area, Bhubaneswar, Odisha",
  },
  ludhiana: {
    state: "Punjab",
    district: "Ludhiana",
    city: "Ludhiana",
    lat: 30.901,
    lng: 75.8573,
    highway: "State Highway",
    address: "Central area, Ludhiana, Punjab",
  },
  amritsar: {
    state: "Punjab",
    district: "Amritsar",
    city: "Amritsar",
    lat: 31.634,
    lng: 74.8723,
    highway: "State Highway",
    address: "Central area, Amritsar, Punjab",
  },
  jaipur: {
    state: "Rajasthan",
    district: "Jaipur",
    city: "Jaipur",
    lat: 26.9124,
    lng: 75.7873,
    highway: "State Highway",
    address: "Central area, Jaipur, Rajasthan",
  },
  jodhpur: {
    state: "Rajasthan",
    district: "Jodhpur",
    city: "Jodhpur",
    lat: 26.2389,
    lng: 73.0243,
    highway: "State Highway",
    address: "Central area, Jodhpur, Rajasthan",
  },
  gangtok: {
    state: "Sikkim",
    district: "East Sikkim",
    city: "Gangtok",
    lat: 27.3389,
    lng: 88.6065,
    highway: "State Highway",
    address: "Central area, Gangtok, Sikkim",
  },
  chennai: {
    state: "Tamil Nadu",
    district: "Chennai",
    city: "Chennai",
    lat: 13.0827,
    lng: 80.2707,
    highway: "State Highway",
    address: "Central area, Chennai, Tamil Nadu",
  },
  coimbatore: {
    state: "Tamil Nadu",
    district: "Coimbatore",
    city: "Coimbatore",
    lat: 11.0168,
    lng: 76.9558,
    highway: "State Highway",
    address: "Central area, Coimbatore, Tamil Nadu",
  },
  madurai: {
    state: "Tamil Nadu",
    district: "Madurai",
    city: "Madurai",
    lat: 9.9252,
    lng: 78.1198,
    highway: "State Highway",
    address: "Central area, Madurai, Tamil Nadu",
  },
  hyderabad: {
    state: "Telangana",
    district: "Hyderabad",
    city: "Hyderabad",
    lat: 17.385,
    lng: 78.4867,
    highway: "State Highway",
    address: "Central area, Hyderabad, Telangana",
  },
  agartala: {
    state: "Tripura",
    district: "West Tripura",
    city: "Agartala",
    lat: 23.8315,
    lng: 91.2868,
    highway: "State Highway",
    address: "Central area, Agartala, Tripura",
  },
  lucknow: {
    state: "Uttar Pradesh",
    district: "Lucknow",
    city: "Lucknow",
    lat: 26.8467,
    lng: 80.9462,
    highway: "State Highway",
    address: "Central area, Lucknow, Uttar Pradesh",
  },
  kanpur: {
    state: "Uttar Pradesh",
    district: "Kanpur Nagar",
    city: "Kanpur",
    lat: 26.4499,
    lng: 80.3319,
    highway: "State Highway",
    address: "Central area, Kanpur, Uttar Pradesh",
  },
  dehradun: {
    state: "Uttarakhand",
    district: "Dehradun",
    city: "Dehradun",
    lat: 30.3165,
    lng: 78.0322,
    highway: "State Highway",
    address: "Central area, Dehradun, Uttarakhand",
  },
  kolkata: {
    state: "West Bengal",
    district: "Kolkata",
    city: "Kolkata",
    lat: 22.5726,
    lng: 88.3639,
    highway: "State Highway",
    address: "Central area, Kolkata, West Bengal",
  },
  delhi: {
    state: "Delhi",
    district: "New Delhi",
    city: "New Delhi",
    lat: 28.6139,
    lng: 77.209,
    highway: "State Highway",
    address: "Central area, New Delhi, Delhi",
  },
  srinagar: {
    state: "Jammu and Kashmir",
    district: "Srinagar",
    city: "Srinagar",
    lat: 34.0837,
    lng: 74.7973,
    highway: "State Highway",
    address: "Central area, Srinagar, Jammu and Kashmir",
  },
};
